version: "3.0"
services:
  db:
    container_name: "avido"
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=avido
      - POSTGRES_PASSWORD=avido
      - POSTGRES_DB=avido
    ports:
      - "5432:5432"
    networks:
      - custom
  db_test:
    container_name: "avido_test_db"
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=avido_test_db
      - POSTGRES_PASSWORD=avido_test_db
      - POSTGRES_DB=avido_test_db
    ports:
      - "5433:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge


#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env
#     depends_on:
#       - db

  

#   nginx:
#   image: nginx:latest
#   volumes:
#     - ./nginx.conf:/etc/nginx/nginx.conf
#   ports:
#     - "80:80"
#   depends_on:
#     - web

# volumes:
#   postgres_data:





